"""add moderation retry metadata

Revision ID: e3dd208c52f3
Revises: f6da7104cb77
Create Date: 2026-08-12 16:30:16.310281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3dd208c52f3'
down_revision: Union[str, Sequence[str], None] = 'f6da7104cb77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderation_results', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('moderation_results', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderation_results', 'last_error')
    op.drop_column('moderation_results', 'retry_count')
    # ### end Alembic commands ###
